// Seed data for Kisan H - Smart Farmer Procurement Schedule & Status Information System

export const MSP_CATALOG = [
  {
    id: "paddy-common",
    name: "Paddy (Common)",
    name_te: "వరి (సాధారణ రకం)",
    name_hi: "धान (सामान्य)",
    msp: 2369,
    marketAvg: 2250,
    unit: "Quintal",
    category: "Cereals",
    maxMoisture: 17,
    season: "Kharif 2025-26",
    priceTrend: "+3.0% YoY",
    icon: "🌾"
  },
  {
    id: "paddy-grade-a",
    name: "Paddy (Grade A / Sona Masoori)",
    name_te: "వరి (గ్రేడ్-ఎ / సోనా మసూరి)",
    name_hi: "धान (ग्रेड-ఎ / सोना मसूरी)",
    msp: 2389,
    marketAvg: 2480,
    unit: "Quintal",
    category: "Cereals",
    maxMoisture: 17,
    season: "Kharif 2025-26",
    priceTrend: "+3.0% YoY",
    icon: "🌾"
  },
  {
    id: "bajra",
    name: "Bajra (Pearl Millet)",
    name_te: "సజ్జలు",
    name_hi: "बाजरा",
    msp: 2775,
    marketAvg: 2650,
    unit: "Quintal",
    category: "Cereals",
    maxMoisture: 12,
    season: "Kharif 2025-26",
    priceTrend: "+5.7% YoY",
    icon: "🌾"
  },
  {
    id: "barley",
    name: "Barley",
    name_te: "బార్లీ",
    name_hi: "जौ",
    msp: 2150,
    marketAvg: 2100,
    unit: "Quintal",
    category: "Cereals",
    maxMoisture: 12,
    season: "Rabi 2026-27",
    priceTrend: "0.0% YoY",
    icon: "🌾"
  },
  {
    id: "jowar-hybrid",
    name: "Jowar (Hybrid)",
    name_te: "జొన్నలు (హైబ్రిడ్)",
    name_hi: "ज्वार (हाइब्रिड)",
    msp: 3699,
    marketAvg: 3550,
    unit: "Quintal",
    category: "Cereals",
    maxMoisture: 12,
    season: "Kharif 2025-26",
    priceTrend: "+5.2% YoY",
    icon: "🌾"
  },
  {
    id: "jowar-maldandi",
    name: "Jowar (Maldandi)",
    name_te: "జొన్నలు (మాల్దండి)",
    name_hi: "ज्वार (मालदंडी)",
    msp: 3749,
    marketAvg: 3680,
    unit: "Quintal",
    category: "Cereals",
    maxMoisture: 12,
    season: "Kharif 2025-26",
    priceTrend: "+5.0% YoY",
    icon: "🌾"
  },
  {
    id: "maize",
    name: "Maize (Corn)",
    name_te: "మొక్కజొన్న",
    name_hi: "मक्का",
    msp: 2400,
    marketAvg: 2310,
    unit: "Quintal",
    category: "Cereals",
    maxMoisture: 14,
    season: "Kharif 2025-26",
    priceTrend: "+7.9% YoY",
    icon: "🌽"
  },
  {
    id: "ragi",
    name: "Ragi (Finger Millet)",
    name_te: "రాగులు",
    name_hi: "रागी",
    msp: 4886,
    marketAvg: 4750,
    unit: "Quintal",
    category: "Cereals",
    maxMoisture: 12,
    season: "Kharif 2025-26",
    priceTrend: "+6.0% YoY",
    icon: "🌾"
  },
  {
    id: "wheat",
    name: "Wheat (Sharbati / HD-2967)",
    name_te: "గోధుమలు",
    name_hi: "गेहूं (शरबती)",
    msp: 2585,
    marketAvg: 2520,
    unit: "Quintal",
    category: "Cereals",
    maxMoisture: 12,
    season: "Rabi 2026-27",
    priceTrend: "+6.6% YoY",
    icon: "🌾"
  },
  {
    id: "copra-ball",
    name: "Copra (Ball)",
    name_te: "కొబ్బరి (బాల్)",
    name_hi: "कोपरा (गोला)",
    msp: 12100,
    marketAvg: 12500,
    unit: "Quintal",
    category: "Commercial Crops",
    maxMoisture: 7,
    season: "2025-26",
    priceTrend: "+4.5% YoY",
    icon: "🥥"
  },
  {
    id: "copra-milling",
    name: "Copra (Milling)",
    name_te: "కొబ్బరి (మిల్లింగ్)",
    name_hi: "कोपरा (मिलिंग)",
    msp: 11582,
    marketAvg: 11900,
    unit: "Quintal",
    category: "Commercial Crops",
    maxMoisture: 7,
    season: "2025-26",
    priceTrend: "+4.3% YoY",
    icon: "🥥"
  },
  {
    id: "bengal-gram",
    name: "Bengal Gram (Chana / Chickpea)",
    name_te: "శనగలు (దేశవాళీ)",
    name_hi: "चना (देसी)",
    msp: 5875,
    marketAvg: 6020,
    unit: "Quintal",
    category: "Pulses",
    maxMoisture: 12,
    season: "Rabi 2026-27",
    priceTrend: "+3.98% YoY",
    icon: "🫘"
  },
  {
    id: "lentil-masur",
    name: "Lentil (Masur)",
    name_te: "మసూర్ పప్పు",
    name_hi: "मसूर",
    msp: 7000,
    marketAvg: 7150,
    unit: "Quintal",
    category: "Pulses",
    maxMoisture: 12,
    season: "Rabi 2026-27",
    priceTrend: "+4.48% YoY",
    icon: "🫘"
  },
  {
    id: "moong",
    name: "Moong (Green Gram)",
    name_te: "పెసలు",
    name_hi: "मूंग",
    msp: 8768,
    marketAvg: 8600,
    unit: "Quintal",
    category: "Pulses",
    maxMoisture: 12,
    season: "Kharif 2025-26",
    priceTrend: "+4.1% YoY",
    icon: "🫘"
  },
  {
    id: "tur-arhar",
    name: "Tur (Arhar / Red Gram)",
    name_te: "కందులు",
    name_hi: "तूर (अरहर)",
    msp: 8000,
    marketAvg: 8250,
    unit: "Quintal",
    category: "Pulses",
    maxMoisture: 12,
    season: "Kharif 2025-26",
    priceTrend: "+5.9% YoY",
    icon: "🫘"
  },
  {
    id: "urad",
    name: "Urad (Black Gram)",
    name_te: "మినుములు",
    name_hi: "उडद",
    msp: 7800,
    marketAvg: 7950,
    unit: "Quintal",
    category: "Pulses",
    maxMoisture: 12,
    season: "Kharif 2025-26",
    priceTrend: "+5.4% YoY",
    icon: "🫘"
  },
  {
    id: "groundnut",
    name: "Groundnut (Pod)",
    name_te: "వేరుశెనగ (కాయలు)",
    name_hi: "मूंगफली (फली)",
    msp: 7263,
    marketAvg: 7400,
    unit: "Quintal",
    category: "Oilseeds",
    maxMoisture: 9,
    season: "Kharif 2025-26",
    priceTrend: "+7.1% YoY",
    icon: "🥜"
  },
  {
    id: "nigerseed",
    name: "Nigerseed",
    name_te: "నైజర్ విత్తనాలు",
    name_hi: "रामतिल",
    msp: 9537,
    marketAvg: 9400,
    unit: "Quintal",
    category: "Oilseeds",
    maxMoisture: 9,
    season: "Kharif 2025-26",
    priceTrend: "+6.0% YoY",
    icon: "🌱"
  },
  {
    id: "mustard",
    name: "Rapeseed / Mustard",
    name_te: "ఆవాలు",
    name_hi: "सरसों",
    msp: 6200,
    marketAvg: 6350,
    unit: "Quintal",
    category: "Oilseeds",
    maxMoisture: 8,
    season: "Rabi 2026-27",
    priceTrend: "+4.20% YoY",
    icon: "🌱"
  },
  {
    id: "safflower",
    name: "Safflower",
    name_te: "కుసుమలు",
    name_hi: "कुसुम",
    msp: 6540,
    marketAvg: 6400,
    unit: "Quintal",
    category: "Oilseeds",
    maxMoisture: 9,
    season: "Rabi 2026-27",
    priceTrend: "+10.10% YoY",
    icon: "🌱"
  },
  {
    id: "sesamum",
    name: "Sesamum (Til)",
    name_te: "నువ్వులు",
    name_hi: "तिल",
    msp: 9846,
    marketAvg: 10100,
    unit: "Quintal",
    category: "Oilseeds",
    maxMoisture: 8,
    season: "Kharif 2025-26",
    priceTrend: "+6.5% YoY",
    icon: "🌱"
  },
  {
    id: "soyabean",
    name: "Soyabean (Yellow)",
    name_te: "సోయాబీన్ (పసుపు)",
    name_hi: "सोयाबीन (पीला)",
    msp: 5328,
    marketAvg: 5100,
    unit: "Quintal",
    category: "Oilseeds",
    maxMoisture: 12,
    season: "Kharif 2025-26",
    priceTrend: "+8.9% YoY",
    icon: "🌱"
  },
  {
    id: "sunflower",
    name: "Sunflower Seed",
    name_te: "ప్రొద్దుతిరుగుడు",
    name_hi: "सूरजमुखी",
    msp: 7721,
    marketAvg: 7600,
    unit: "Quintal",
    category: "Oilseeds",
    maxMoisture: 9,
    season: "Kharif 2025-26",
    priceTrend: "+5.6% YoY",
    icon: "🌻"
  },
  {
    id: "jute",
    name: "Jute",
    name_te: "జనపనార",
    name_hi: "जूट",
    msp: 5650,
    marketAvg: 5800,
    unit: "Quintal",
    category: "Commercial Crops",
    maxMoisture: 14,
    season: "2025-26",
    priceTrend: "+5.0% YoY",
    icon: "🧶"
  },
  {
    id: "cotton-long",
    name: "Cotton (Long Staple)",
    name_te: "పత్తి (పొడుగు పింజ)",
    name_hi: "कपास (लंबा रेशा)",
    msp: 8110,
    marketAvg: 7950,
    unit: "Quintal",
    category: "Fiber",
    maxMoisture: 12,
    season: "Kharif 2025-26",
    priceTrend: "+7.8% YoY",
    icon: "☁️"
  },
  {
    id: "cotton-medium",
    name: "Cotton (Medium Staple)",
    name_te: "పత్తి (మధ్యస్థ పింజ)",
    name_hi: "कपास (मध्यम रेशा)",
    msp: 7710,
    marketAvg: 7600,
    unit: "Quintal",
    category: "Fiber",
    maxMoisture: 12,
    season: "Kharif 2025-26",
    priceTrend: "+7.0% YoY",
    icon: "☁️"
  },
  {
    id: "sugarcane",
    name: "Sugarcane (FRP)",
    name_te: "చెరకు",
    name_hi: "गन्ना",
    msp: 355,
    marketAvg: 365,
    unit: "Quintal",
    category: "Commercial Crops",
    maxMoisture: 0,
    season: "2025-26",
    priceTrend: "+4.4% YoY",
    icon: "🎋"
  },
  {
    id: "chilli",
    name: "Red Chilli (Teja / Guntur)",
    name_te: "ఎండు మిర్చి (తేజ / గుంటూరు)",
    name_hi: "लाल मिर्च (तेजा / गुंटूर)",
    msp: 18500,
    marketAvg: 19800,
    unit: "Quintal",
    category: "Spices",
    maxMoisture: 10,
    season: "Rabi 2026",
    priceTrend: "+12.4% YoY",
    icon: "🌶️"
  },
  {
    id: "turmeric",
    name: "Turmeric (Nizamabad Finger)",
    name_te: "పసుపు (నిజామాబాద్ కొమ్ములు)",
    name_hi: "हल्दी (निजामाबाद)",
    msp: 13500,
    marketAvg: 14200,
    unit: "Quintal",
    category: "Spices",
    maxMoisture: 11,
    season: "Rabi 2026",
    priceTrend: "+8.5% YoY",
    icon: "🟡"
  }
];

export const INITIAL_CENTRES = [
  {
    id: "PPC-TS-01",
    name: "Gorakhpur Krishi Utpadan Mandi Samiti (PPC-01)",
    name_te: "గోరఖ్‌పూర్ వ్యవసాయ మార్కెట్ యార్డ్ (PPC-01)",
    name_hi: "गोरखपुर कृषि उत्पादन मंडी समिति (PPC-01)",
    type: "Krishi Utpadan Mandi Samiti (KUMS) / Main Procurement Yard",
    type_te: "వ్యవసాయ మార్కెట్ కమిటీ (AMC) / సేకరణ కేంద్రం",
    type_hi: "कृषि उत्पादन मंडी समिति (KUMS) / मुख्य क्रय यार्ड",
    district: "Gorakhpur",
    mandal: "Gorakhpur Sadar",
    state: "Uttar Pradesh",
    address: "Mandi Parishad Yard, Rustampur, Gorakhpur - 273001",
    lat: 26.7605,
    lng: 83.3894,
    status: "open", // open, closed, break, quota_full
    statusReason: "Normal operations active. 4 weighbridges operational.",
    statusReason_te: "సాధారణ సేకరణ జరుగుతోంది. 4 వేబ్రిడ్జిలు పని చేస్తున్నాయి.",
    statusReason_hi: "सामान्य कार्य जारी है। 4 धर्मकांटे चालू हैं।",
    timings: {
      open: "08:00 AM",
      close: "05:30 PM",
      lunchBreak: "01:00 PM - 02:00 PM",
      workingDays: "Monday - Saturday (Sunday Closed)"
    },
    acceptedCrops: [
      {
        cropId: "paddy-grade-a",
        name: "Paddy (Grade A / Sona Masoori)",
        name_te: "వరి (గ్రేడ్-ఎ)",
        name_hi: "धान (ग्रेड-ए / सोना मसूरी)",
        msp: 2389,
        bonus: 500, // Government incentive bonus
        dailyQuotaQuintals: 2500,
        procuredTodayQuintals: 1420,
        maxMoisture: 17,
        status: "accepting" // accepting, full, paused
      },
      {
        cropId: "wheat",
        name: "Wheat (Sharbati / HD-2967)",
        name_te: "గోధుమలు",
        name_hi: "गेहूं (शरबती)",
        msp: 2585,
        bonus: 0,
        dailyQuotaQuintals: 1800,
        procuredTodayQuintals: 850,
        maxMoisture: 12,
        status: "accepting"
      },
      {
        cropId: "bengal-gram",
        name: "Bengal Gram (Chana)",
        name_te: "శనగలు",
        name_hi: "चना (देसी)",
        msp: 5875,
        bonus: 0,
        dailyQuotaQuintals: 1200,
        procuredTodayQuintals: 620,
        maxMoisture: 12,
        status: "accepting"
      },
      {
        cropId: "maize",
        name: "Maize (Corn)",
        name_te: "మొక్కజొన్న",
        name_hi: "मक्का",
        msp: 2400,
        bonus: 0,
        dailyQuotaQuintals: 1500,
        procuredTodayQuintals: 1350,
        maxMoisture: 14,
        status: "accepting"
      },
      {
        cropId: "paddy-common",
        name: "Paddy (Common)",
        name_te: "వరి (సాధారణ రకం)",
        name_hi: "धान (सामान्य)",
        msp: 2369,
        bonus: 500,
        dailyQuotaQuintals: 2000,
        procuredTodayQuintals: 1120,
        maxMoisture: 17,
        status: "accepting"
      },
      {
        cropId: "cotton-long",
        name: "Cotton (Long Staple)",
        name_te: "పత్తి (పొడుగు పింజ)",
        name_hi: "कपास (लंबा रेशा)",
        msp: 8110,
        bonus: 0,
        dailyQuotaQuintals: 800,
        procuredTodayQuintals: 310,
        maxMoisture: 12,
        status: "accepting"
      },
      {
        cropId: "soyabean",
        name: "Soyabean (Yellow)",
        name_te: "సోయాబీన్ (పసుపు)",
        name_hi: "सोयाबीन (पीला)",
        msp: 5328,
        bonus: 0,
        dailyQuotaQuintals: 900,
        procuredTodayQuintals: 415,
        maxMoisture: 12,
        status: "accepting"
      },
      {
        cropId: "chilli",
        name: "Red Chilli (Teja / Guntur)",
        name_te: "ఎండు మిర్చి (తేజ / గుంటూరు)",
        name_hi: "लाल मिर्च (तेजा / गुंटूर)",
        msp: 18500,
        bonus: 0,
        dailyQuotaQuintals: 300,
        procuredTodayQuintals: 95,
        maxMoisture: 10,
        status: "accepting"
      },
      {
        cropId: "turmeric",
        name: "Turmeric (Nizamabad Finger)",
        name_te: "పసుపు (నిజామాబాద్ కొమ్ములు)",
        name_hi: "हल्दी (निजामाबाद)",
        msp: 13500,
        bonus: 0,
        dailyQuotaQuintals: 250,
        procuredTodayQuintals: 60,
        maxMoisture: 11,
        status: "accepting"
      },
      {
        cropId: "groundnut",
        name: "Groundnut (Pod)",
        name_te: "వేరుశెనగ (కాయలు)",
        name_hi: "मूंगफली (फली)",
        msp: 7263,
        bonus: 0,
        dailyQuotaQuintals: 600,
        procuredTodayQuintals: 210,
        maxMoisture: 9,
        status: "accepting"
      }
    ],
    queue: {
      totalTokensIssuedToday: 68,
      currentlyServingToken: "KST-042",
      activeQueueCount: 14,
      avgMinutesPerToken: 8,
      estimatedWaitTimeMinutes: 45
    },
    facilities: {
      coveredYard: true,
      electronicWeighbridge: true,
      moistureTestingLab: true,
      drinkingWater: true,
      canteen: true,
      restingShed: true,
      gunnyBagsStock: 14500,
      storageCapacityQuintals: 30000,
      occupiedCapacityQuintals: 16800
    },
    contact: {
      officerName: "R.K. Srivastava (Mandi Sachiv)",
      phone: "+91 94151 23456",
      helpdesk: "1800-180-1551"
    },
    rating: 4.8,
    reviewsCount: 312
  },
  {
    id: "PPC-TS-02",
    name: "Kaptanganj PCF Paddy Procurement Centre",
    name_te: "కప్తాన్‌గంజ్ పిసిఎఫ్ వరి సేకరణ కేంద్రం",
    name_hi: "कप्तानगंज पीसीएफ धान क्रय केंद्र",
    type: "Provincial Cooperative Federation (PCF) Centre",
    type_te: "ప్రాథమిక వ్యవసాయ పరపతి సంఘం (PACS)",
    type_hi: "प्रांतीय सहकारी संघ (PCF) केंद्र",
    district: "Kushinagar",
    mandal: "Kaptanganj",
    state: "Uttar Pradesh",
    address: "PCF Godown Complex, Near NH-28, Kaptanganj, Kushinagar - 274401",
    lat: 26.7977,
    lng: 83.7570,
    status: "open",
    statusReason: "High moisture testing underway. Please ensure paddy moisture < 17%.",
    statusReason_te: "తేమ శాతం తనిఖీ జరుగుతోంది. వడ్లలో తేమ 17% కంటే తక్కువ ఉండేలా చూసుకోండి.",
    statusReason_hi: "नमी की गहन जांच जारी है। कृपया सुनिश्चित करें कि धान की नमी 17% से कम हो।",
    timings: {
      open: "08:30 AM",
      close: "05:00 PM",
      lunchBreak: "01:00 PM - 01:45 PM",
      workingDays: "Monday - Saturday"
    },
    acceptedCrops: [
      {
        cropId: "paddy-common",
        name: "Paddy (Common)",
        name_te: "వరి (సాధారణ రకం)",
        name_hi: "धान (सामान्य)",
        msp: 2369,
        bonus: 500,
        dailyQuotaQuintals: 2000,
        procuredTodayQuintals: 1680,
        maxMoisture: 17,
        status: "accepting"
      },
      {
        cropId: "paddy-grade-a",
        name: "Paddy (Grade A)",
        name_te: "వరి (గ్రేడ్-ఎ)",
        name_hi: "धान (ग्रेड-ए / सोना मसूरी)",
        msp: 2389,
        bonus: 500,
        dailyQuotaQuintals: 1500,
        procuredTodayQuintals: 920,
        maxMoisture: 17,
        status: "accepting"
      }
    ],
    queue: {
      totalTokensIssuedToday: 52,
      currentlyServingToken: "KST-036",
      activeQueueCount: 9,
      avgMinutesPerToken: 10,
      estimatedWaitTimeMinutes: 30
    },
    facilities: {
      coveredYard: true,
      electronicWeighbridge: true,
      moistureTestingLab: true,
      drinkingWater: true,
      canteen: false,
      restingShed: true,
      gunnyBagsStock: 8200,
      storageCapacityQuintals: 15000,
      occupiedCapacityQuintals: 11200
    },
    contact: {
      officerName: "V.N. Tiwari (PCF Secretary)",
      phone: "+91 94508 87654",
      helpdesk: "05564-220111"
    },
    rating: 4.6,
    reviewsCount: 184
  },
  {
    id: "PPC-TS-03",
    name: "Deoria Krishi Utpadan Mandi Samiti (Wheat & Grain Yard)",
    name_te: "డియోరియా వ్యవసాయ మార్కెట్ యార్డ్ (గోధుమలు & ధాన్యం)",
    name_hi: "देवरिया कृषि उत्पादन मंडी समिति (गेहूं एवं अनाज यार्ड)",
    type: "Specialized Commodity Market",
    type_te: "ప్రత్యేక వ్యవసాయ మార్కెట్ యార్డ్",
    type_hi: "विशेष जिंस मंडी",
    district: "Deoria",
    mandal: "Deoria Sadar",
    state: "Uttar Pradesh",
    address: "Mandi Samiti Yard, Barhaj Road, Deoria - 274001",
    lat: 26.5024,
    lng: 83.7791,
    status: "open",
    statusReason: "Electronic e-NAM auction & Direct MSP procurement active.",
    statusReason_te: "ఈ-నామ్ వేలం మరియు డైరెక్ట్ ఎంఎస్‌పీ సేకరణ నడుస్తోంది.",
    statusReason_hi: "इलेक्ट्रॉनिक ई-नाम नीलामी एवं सीधी एमएसपी खरीद जारी है।",
    timings: {
      open: "08:00 AM",
      close: "06:00 PM",
      lunchBreak: "01:00 PM - 02:00 PM",
      workingDays: "Monday - Friday (Sat/Sun Maintenance)"
    },
    acceptedCrops: [
      {
        cropId: "wheat",
        name: "Wheat (Sharbati / HD-2967)",
        name_te: "గోధుమలు",
        name_hi: "गेहूं (शरबती)",
        msp: 2585,
        bonus: 0,
        dailyQuotaQuintals: 3000,
        procuredTodayQuintals: 1890,
        maxMoisture: 12,
        status: "accepting"
      },
      {
        cropId: "bengal-gram",
        name: "Bengal Gram (Chana)",
        name_te: "శనగలు",
        name_hi: "चना (देसी)",
        msp: 5875,
        bonus: 0,
        dailyQuotaQuintals: 2200,
        procuredTodayQuintals: 1540,
        maxMoisture: 12,
        status: "accepting"
      },
      {
        cropId: "maize",
        name: "Maize",
        name_te: "మొక్కజొన్న",
        name_hi: "मक्का",
        msp: 2400,
        bonus: 0,
        dailyQuotaQuintals: 1600,
        procuredTodayQuintals: 880,
        maxMoisture: 14,
        status: "accepting"
      }
    ],
    queue: {
      totalTokensIssuedToday: 84,
      currentlyServingToken: "KST-058",
      activeQueueCount: 18,
      avgMinutesPerToken: 7,
      estimatedWaitTimeMinutes: 50
    },
    facilities: {
      coveredYard: true,
      electronicWeighbridge: true,
      moistureTestingLab: true,
      drinkingWater: true,
      canteen: true,
      restingShed: true,
      gunnyBagsStock: 22000,
      storageCapacityQuintals: 45000,
      occupiedCapacityQuintals: 28400
    },
    contact: {
      officerName: "P. Ravindra Pandey (Mandi Secretary)",
      phone: "+91 94501 54321",
      helpdesk: "05568-234567"
    },
    rating: 4.9,
    reviewsCount: 420
  },
  {
    id: "PPC-TS-04",
    name: "Bansgaon PCF Godown Procurement Centre",
    name_te: "బాన్స్‌గావ్ పిసిఎఫ్ గోడౌన్ సేకరణ కేంద్రం",
    name_hi: "बांसगांव पीसीएफ गोदाम क्रय केंद्र",
    type: "Provincial Cooperative Federation (PCF) Godown",
    type_te: "సహకార సంఘం (PCF) గోడౌన్",
    type_hi: "प्रांतीय सहकारी संघ (PCF) गोदाम",
    district: "Gorakhpur",
    mandal: "Bansgaon",
    state: "Uttar Pradesh",
    address: "PCF Godown Complex, Bansgaon Bazar, Gorakhpur - 273151",
    lat: 26.5390,
    lng: 83.4505,
    status: "break",
    statusReason: "Lunch break in progress. Weighbridge resumes at 02:00 PM.",
    statusReason_te: "భోజన విరామం. మధ్యాహ్నం 2:00 గంటలకు తూకం తిరిగి ప్రారంభమవుతుంది.",
    statusReason_hi: "भोजन अवकाश चल रहा है। धर्मकांटा दोपहर 2:00 बजे पुनः शुरू होगा।",
    timings: {
      open: "09:00 AM",
      close: "05:00 PM",
      lunchBreak: "01:00 PM - 02:00 PM",
      workingDays: "Monday - Saturday"
    },
    acceptedCrops: [
      {
        cropId: "wheat",
        name: "Wheat (Sharbati)",
        name_te: "గోధుమలు",
        name_hi: "गेहूं (शरबती)",
        msp: 2585,
        bonus: 0,
        dailyQuotaQuintals: 3500,
        procuredTodayQuintals: 2100,
        maxMoisture: 12,
        status: "accepting"
      },
      {
        cropId: "paddy-common",
        name: "Paddy (Common)",
        name_te: "వరి",
        name_hi: "धान (सामान्य)",
        msp: 2369,
        bonus: 500,
        dailyQuotaQuintals: 1500,
        procuredTodayQuintals: 950,
        maxMoisture: 17,
        status: "accepting"
      }
    ],
    queue: {
      totalTokensIssuedToday: 45,
      currentlyServingToken: "KST-030",
      activeQueueCount: 11,
      avgMinutesPerToken: 9,
      estimatedWaitTimeMinutes: 65
    },
    facilities: {
      coveredYard: true,
      electronicWeighbridge: true,
      moistureTestingLab: true,
      drinkingWater: true,
      canteen: true,
      restingShed: true,
      gunnyBagsStock: 11000,
      storageCapacityQuintals: 25000,
      occupiedCapacityQuintals: 18200
    },
    contact: {
      officerName: "T. Srivastava (PCF Incharge)",
      phone: "+91 93910 99887",
      helpdesk: "1800-120-2277"
    },
    rating: 4.5,
    reviewsCount: 160
  },
  {
    id: "PPC-AP-05",
    name: "Basti Krishi Utpadan Mandi Samiti (Largest Yard - Purvanchal)",
    name_te: "బస్తీ వ్యవసాయ మార్కెట్ యార్డ్ (పూర్వాంచల్ అతిపెద్ద మార్కెట్)",
    name_hi: "बस्ती कृषि उत्पादन मंडी समिति (पूर्वांचल की सबसे बड़ी मंडी)",
    type: "Krishi Utpadan Mandi Samiti - Regional Hub Yard",
    type_te: "వ్యవసాయ మార్కెట్ యార్డ్ - ప్రాంతీయ కేంద్రం",
    type_hi: "कृषि उत्पादन मंडी समिति - क्षेत्रीय केंद्र यार्ड",
    district: "Basti",
    mandal: "Basti Sadar",
    state: "Uttar Pradesh",
    address: "Mandi Samiti Yard, GT Road, Basti - 272001",
    lat: 26.8148,
    lng: 82.7274,
    status: "open",
    statusReason: "Spot payment advice generation and priority weighment for wheat & paddy.",
    statusReason_te: "మిర్చి నాణ్యతా పరీక్షలు మరియు కోల్డ్ స్టోరేజ్ అలాట్‌మెంట్ సాగుతోంది.",
    statusReason_hi: "तत्काल भुगतान सूचना जनरेशन एवं गेहूं व धान के लिए प्राथमिकता तौल।",
    timings: {
      open: "07:30 AM",
      close: "06:30 PM",
      lunchBreak: "01:00 PM - 02:00 PM",
      workingDays: "Monday - Saturday"
    },
    acceptedCrops: [
      {
        cropId: "wheat",
        name: "Wheat (Sharbati / HD-2967)",
        name_te: "గోధుమలు",
        name_hi: "गेहूं (शरबती)",
        msp: 2585,
        bonus: 1000,
        dailyQuotaQuintals: 5000,
        procuredTodayQuintals: 3400,
        maxMoisture: 12,
        status: "accepting"
      },
      {
        cropId: "paddy-grade-a",
        name: "Paddy (Grade A)",
        name_te: "వరి (గ్రేడ్-ఎ)",
        name_hi: "धान (ग्रेड-ए / सोना मसूरी)",
        msp: 2389,
        bonus: 500,
        dailyQuotaQuintals: 2000,
        procuredTodayQuintals: 1100,
        maxMoisture: 17,
        status: "accepting"
      },
      {
        cropId: "bengal-gram",
        name: "Bengal Gram (Chana)",
        name_te: "శనగలు",
        name_hi: "चना (देसी)",
        msp: 5875,
        bonus: 0,
        dailyQuotaQuintals: 1500,
        procuredTodayQuintals: 720,
        maxMoisture: 12,
        status: "accepting"
      }
    ],
    queue: {
      totalTokensIssuedToday: 112,
      currentlyServingToken: "KST-089",
      activeQueueCount: 16,
      avgMinutesPerToken: 6,
      estimatedWaitTimeMinutes: 35
    },
    facilities: {
      coveredYard: true,
      electronicWeighbridge: true,
      moistureTestingLab: true,
      drinkingWater: true,
      canteen: true,
      restingShed: true,
      gunnyBagsStock: 35000,
      storageCapacityQuintals: 80000,
      occupiedCapacityQuintals: 52000
    },
    contact: {
      officerName: "B. Shashi Bhushan (Mandi Nodal Officer)",
      phone: "+91 94412 88990",
      helpdesk: "1902"
    },
    rating: 4.9,
    reviewsCount: 580
  },
  {
    id: "PPC-TS-06",
    name: "Campierganj UPSWC Godown Procurement Centre",
    name_te: "కాంపియర్‌గంజ్ యుపిఎస్‌డబ్ల్యుసి గోడౌన్ సేకరణ కేంద్రం",
    name_hi: "कैंपियरगंज यूपीएसडब्ल्यूसी गोदाम क्रय केंद्र",
    type: "UP State Warehousing Corporation (UPSWC) Godown",
    type_te: "మార్క్‌ఫెడ్ కొనుగోలు కేంద్రం",
    type_hi: "यूपी राज्य भंडारण निगम (UPSWC) गोदाम",
    district: "Gorakhpur",
    mandal: "Campierganj",
    state: "Uttar Pradesh",
    address: "UPSWC Godown Complex, Near Nepal Border Road, Campierganj, Gorakhpur - 273157",
    lat: 26.9578,
    lng: 83.3318,
    status: "quota_full",
    statusReason: "Daily procurement quota filled for today (3000 Quintals reached). Reopens tomorrow 8 AM.",
    statusReason_te: "ఈ రోజు సేకరణ కోటా పూర్తయింది. రేపు ఉదయం 8:00 గంటలకు తిరిగి ప్రారంభం.",
    statusReason_hi: "आज की दैनिक खरीद कोटा पूर्ण हो गई है (3000 क्विंटल)। कल सुबह 8 बजे पुनः खुलेगा।",
    timings: {
      open: "08:00 AM",
      close: "05:00 PM",
      lunchBreak: "01:00 PM - 01:45 PM",
      workingDays: "Monday - Saturday"
    },
    acceptedCrops: [
      {
        cropId: "paddy-grade-a",
        name: "Paddy (Grade A)",
        name_te: "వరి (గ్రేడ్-ఎ)",
        name_hi: "धान (ग्रेड-ए / सोना मसूरी)",
        msp: 2389,
        bonus: 500,
        dailyQuotaQuintals: 3000,
        procuredTodayQuintals: 3000,
        maxMoisture: 17,
        status: "full"
      },
      {
        cropId: "maize",
        name: "Maize",
        name_te: "మొక్కజొన్న",
        name_hi: "मक्का",
        msp: 2400,
        bonus: 0,
        dailyQuotaQuintals: 1500,
        procuredTodayQuintals: 1500,
        maxMoisture: 14,
        status: "full"
      }
    ],
    queue: {
      totalTokensIssuedToday: 95,
      currentlyServingToken: "KST-095",
      activeQueueCount: 0,
      avgMinutesPerToken: 8,
      estimatedWaitTimeMinutes: 0
    },
    facilities: {
      coveredYard: true,
      electronicWeighbridge: true,
      moistureTestingLab: true,
      drinkingWater: true,
      canteen: true,
      restingShed: true,
      gunnyBagsStock: 18000,
      storageCapacityQuintals: 40000,
      occupiedCapacityQuintals: 39500
    },
    contact: {
      officerName: "Ch. Ramesh Chandra (UPSWC DM)",
      phone: "+91 94906 11223",
      helpdesk: "0551-224455"
    },
    rating: 4.7,
    reviewsCount: 245
  },
  {
    id: "PPC-TS-07",
    name: "Chauri Chaura PCF Women SHG Paddy Procurement Centre",
    name_te: "చౌరీ చౌరా పిసిఎఫ్ మహిళా స్వయం సహాయక బృంద వరి సేకరణ కేంద్రం",
    name_hi: "चौरी चौरा पीसीएफ महिला स्वयं सहायता समूह धान क्रय केंद्र",
    type: "PCF / Women Self-Help Group (SHG) Procurement Centre",
    type_te: "ఐకేపీ మహిళా సమాఖ్య కేంద్రం",
    type_hi: "पीसीएफ / महिला स्वयं सहायता समूह (SHG) क्रय केंद्र",
    district: "Gorakhpur",
    mandal: "Chauri Chaura",
    state: "Uttar Pradesh",
    address: "Near Chauri Chaura Railway Station, Gorakhpur - 273201",
    lat: 26.7363,
    lng: 83.5610,
    status: "open",
    statusReason: "Spot payment advice generation and immediate truck loading.",
    statusReason_te: "స్పాట్ పేమెంట్ రసీదు మరియు వెంటనే లారీ లోడింగ్ జరుగుతోంది.",
    statusReason_hi: "तत्काल भुगतान सूचना जनरेशन एवं तुरंत ट्रक लोडिंग।",
    timings: {
      open: "08:30 AM",
      close: "05:30 PM",
      lunchBreak: "01:00 PM - 02:00 PM",
      workingDays: "Monday - Saturday"
    },
    acceptedCrops: [
      {
        cropId: "paddy-common",
        name: "Paddy (Common)",
        name_te: "వరి (సాధారణ)",
        name_hi: "धान (सामान्य)",
        msp: 2369,
        bonus: 500,
        dailyQuotaQuintals: 1800,
        procuredTodayQuintals: 1100,
        maxMoisture: 17,
        status: "accepting"
      },
      {
        cropId: "paddy-grade-a",
        name: "Paddy (Grade A)",
        name_te: "వరి (గ్రేడ్-ఎ)",
        name_hi: "धान (ग्रेड-ए / सोना मसूरी)",
        msp: 2389,
        bonus: 500,
        dailyQuotaQuintals: 1200,
        procuredTodayQuintals: 740,
        maxMoisture: 17,
        status: "accepting"
      }
    ],
    queue: {
      totalTokensIssuedToday: 38,
      currentlyServingToken: "KST-027",
      activeQueueCount: 7,
      avgMinutesPerToken: 8,
      estimatedWaitTimeMinutes: 25
    },
    facilities: {
      coveredYard: false,
      electronicWeighbridge: true,
      moistureTestingLab: true,
      drinkingWater: true,
      canteen: false,
      restingShed: true,
      gunnyBagsStock: 9500,
      storageCapacityQuintals: 12000,
      occupiedCapacityQuintals: 7800
    },
    contact: {
      officerName: "Smt. Sarita Devi (SHG Coordinator)",
      phone: "+91 97012 33445",
      helpdesk: "1800-180-1551"
    },
    rating: 4.7,
    reviewsCount: 140
  }
];

export const INITIAL_TOKENS = [
  {
    tokenNumber: "KST-041",
    centreId: "PPC-TS-01",
    centreName: "Gorakhpur Krishi Utpadan Mandi Samiti (PPC-01)",
    farmerName: "B. Mahesh Yadav",
    farmerName_te: "బి. మహేష్ యాదవ్",
    phone: "9848011223",
    aadhaarLast4: "4589",
    passbookNo: "UP-GKP-2024-9912",
    cropId: "paddy-grade-a",
    cropName: "Paddy (Grade A / Sona Masoori)",
    quantityQuintals: 45,
    vehicleType: "Tractor-Trolley (ट्रैक्टर)",
    vehicleNumber: "UP 53 TA 4421",
    slotDate: "2026-08-22",
    slotTime: "10:30 AM - 11:30 AM",
    status: "COMPLETED", // BOOKED, CHECKED_IN, TESTING, WEIGHING, PAID, COMPLETED, CANCELLED
    moistureMeasured: 15.8,
    gradeAssigned: "Grade-A Super",
    totalWeightQuintals: 45.2,
    netPayableAmount: 127464, // (45.2 * (2320 + 500))
    issuedAt: "2026-08-22T08:15:00.000Z",
    completedAt: "2026-08-22T10:45:00.000Z"
  },
  {
    tokenNumber: "KST-042",
    centreId: "PPC-TS-01",
    centreName: "Gorakhpur Krishi Utpadan Mandi Samiti (PPC-01)",
    farmerName: "G. Ramchandra Pandey",
    farmerName_te: "జి. రామచంద్ర పాండే",
    phone: "9440199882",
    aadhaarLast4: "7123",
    passbookNo: "UP-GKP-2023-8821",
    cropId: "paddy-grade-a",
    cropName: "Paddy (Grade A / Sona Masoori)",
    quantityQuintals: 60,
    vehicleType: "Mini-Truck (डीसीएम / बोलेरो)",
    vehicleNumber: "UP 53 UB 1092",
    slotDate: "2026-08-22",
    slotTime: "11:00 AM - 12:00 PM",
    status: "WEIGHING",
    moistureMeasured: 16.2,
    gradeAssigned: "Grade-A Standard",
    totalWeightQuintals: null,
    netPayableAmount: null,
    issuedAt: "2026-08-22T08:30:00.000Z"
  },
  {
    tokenNumber: "KST-043",
    centreId: "PPC-TS-01",
    centreName: "Gorakhpur Krishi Utpadan Mandi Samiti (PPC-01)",
    farmerName: "K. Srinivas Mishra",
    farmerName_te: "కె. శ్రీనివాస్ మిశ్రా",
    phone: "9121233445",
    aadhaarLast4: "9012",
    passbookNo: "UP-GKP-2025-1102",
    cropId: "wheat",
    cropName: "Wheat (Sharbati / HD-2967)",
    quantityQuintals: 30,
    vehicleType: "Tractor-Trolley (ट्रैक्टर)",
    vehicleNumber: "UP 53 TC 8831",
    slotDate: "2026-08-22",
    slotTime: "11:30 AM - 12:30 PM",
    status: "TESTING",
    moistureMeasured: 11.5,
    gradeAssigned: null,
    totalWeightQuintals: null,
    netPayableAmount: null,
    issuedAt: "2026-08-22T09:00:00.000Z"
  },
  {
    tokenNumber: "KST-044",
    centreId: "PPC-TS-01",
    centreName: "Gorakhpur Krishi Utpadan Mandi Samiti (PPC-01)",
    farmerName: "Ramesh Kumar (You)",
    farmerName_te: "రమేష్ కుమార్",
    phone: "9876543210",
    aadhaarLast4: "2345",
    passbookNo: "UP-GKP-2026-0044",
    cropId: "paddy-grade-a",
    cropName: "Paddy (Grade A / Sona Masoori)",
    quantityQuintals: 50,
    vehicleType: "Tractor-Trolley (ट्रैक्टर)",
    vehicleNumber: "UP 53 AA 5555",
    slotDate: "2026-08-22",
    slotTime: "12:00 PM - 01:00 PM",
    status: "CHECKED_IN",
    moistureMeasured: null,
    gradeAssigned: null,
    totalWeightQuintals: null,
    netPayableAmount: null,
    issuedAt: "2026-08-22T09:15:00.000Z"
  },
  {
    tokenNumber: "KST-045",
    centreId: "PPC-TS-01",
    centreName: "Gorakhpur Krishi Utpadan Mandi Samiti (PPC-01)",
    farmerName: "P. Lakshmi Devi",
    farmerName_te: "పి. లక్ష్మీ దేవి",
    phone: "9988776655",
    aadhaarLast4: "6678",
    passbookNo: "UP-GKP-2024-5541",
    cropId: "bengal-gram",
    cropName: "Bengal Gram (Chana)",
    quantityQuintals: 20,
    vehicleType: "Auto Trolley (ऑटो ट्रॉली)",
    vehicleNumber: "UP 53 TR 7712",
    slotDate: "2026-08-22",
    slotTime: "02:00 PM - 03:00 PM",
    status: "BOOKED",
    moistureMeasured: null,
    gradeAssigned: null,
    totalWeightQuintals: null,
    netPayableAmount: null,
    issuedAt: "2026-08-22T09:45:00.000Z"
  }
];

export const INITIAL_ANNOUNCEMENTS = [
  {
    id: "ANN-001",
    centreId: "ALL",
    centreName: "All Procurement Centres (जनपद व्यापी)",
    title: "Government Bonus: ₹500/Quintal on Fine Grade Paddy",
    title_te: "ప్రభుత్వ బోనస్: సన్న వడ్లకు క్వింటాకు ₹500 అదనపు బోనస్ జమ",
    title_hi: "सरकारी बोनस: बारीक धान पर ₹500 प्रति क्विंटल अतिरिक्त प्रोत्साहन राशि",
    message: "Uttar Pradesh state government has confirmed immediate ₹500 per quintal incentive directly into farmer bank accounts within 48 hours of weighment.",
    message_te: "రైతులు కొనుగోలు కేంద్రాల్లో ధాన్యం విక్రయించిన 48 గంటల్లోగా క్వింటాకు ₹500 బోనస్ నేరుగా వారి బ్యాంక్ ఖాతాల్లో జమ చేయబడుతుంది.",
    message_hi: "उत्तर प्रदेश राज्य सरकार ने वजन के 48 घंटों के भीतर किसानों के बैंक खातों में सीधे ₹500 प्रति क्विंटल प्रोत्साहन राशि की पुष्टि की है।",
    severity: "success", // success, warning, info, alert
    timestamp: "2026-08-22T08:00:00.000Z",
    isActive: true
  },
  {
    id: "ANN-002",
    centreId: "PPC-TS-01",
    centreName: "Gorakhpur Krishi Utpadan Mandi Samiti",
    title: "Weather Alert: Evening Rain Forecast - Covered Shed Priority",
    title_te: "వాతావరణ హెచ్చరిక: సాయంత్రం వర్షం సూచన - షెడ్ల కేటాయింపు",
    title_hi: "मौसम चेतावनी: शाम को बारिश की संभावना - शेड आवंटन प्राथमिकता",
    message: "Farmers bringing open trolleys are advised to reach before 3:00 PM. Covered Shed-A and Shed-B have been allocated for tarpaulin-free unloading.",
    message_te: "సాయంత్రం చిరుజల్లులు కురిసే అవకాశం ఉన్నందున రైతులు మధ్యాహ్నం 3 గంటలలోపు కేంద్రానికి చేరుకోవాల్సిందిగా విజ్ఞప్తి. షెడ్లు సిద్ధంగా ఉన్నాయి.",
    message_hi: "खुली ट्रॉली लाने वाले किसानों को शाम 3:00 बजे से पहले पहुंचने की सलाह दी जाती है। बिना तिरपाल के उतराई हेतु शेड-ए एवं शेड-बी आवंटित किए गए हैं।",
    severity: "warning",
    timestamp: "2026-08-22T09:30:00.000Z",
    isActive: true
  },
  {
    id: "ANN-003",
    centreId: "PPC-TS-02",
    centreName: "Kaptanganj PCF Paddy PPC",
    title: "Gunny Bags Stock Arrived (10,000 Bags Added)",
    title_te: "గన్నీ సంచుల నిల్వలు వచ్చాయి (10,000 అదనపు సంచులు)",
    title_hi: "बारदाना (बोरी) नया स्टॉक उपलब्ध",
    message: "Sufficient gunny bags are now available at Kaptanganj PCF. No bag shortage delay.",
    message_te: "కప్తాన్‌గంజ్ కేంద్రంలో కొత్తగా 10,000 గన్నీ సంచులు అందుబాటులోకి వచ్చాయి. ఎటువంటి కొరత లేదు.",
    message_hi: "कप्तानगंज पीसीएफ में अब पर्याप्त बारदाना (बोरी) उपलब्ध है। बोरी की कमी से कोई देरी नहीं होगी।",
    severity: "info",
    timestamp: "2026-08-22T10:00:00.000Z",
    isActive: true
  }
];
