import jsPDF from 'jspdf';
import QRCode from 'qrcode';
import { DigitalToken } from '../types';

export async function generateTokenPdf(token: DigitalToken): Promise<void> {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  // Generate QR Code as Data URL
  const qrData = JSON.stringify({
    token: token.tokenNumber,
    centreId: token.centreId,
    farmer: token.farmerName,
    phone: token.phone,
    crop: token.cropName,
    qty: token.quantityQuintals,
    slot: token.slotDate + ' ' + token.slotTime,
    vehicle: token.vehicleNumber
  });

  const qrDataUrl = await QRCode.toDataURL(qrData, {
    margin: 1,
    width: 250,
    color: {
      dark: '#14532d',
      light: '#ffffff'
    }
  });

  // Header Banner
  doc.setFillColor(22, 163, 74); // Agri Green #16a34a
  doc.rect(0, 0, 210, 32, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('KISAN SETU | SMART PROCUREMENT HUB', 105, 14, { align: 'center' });

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text('Official Farmer Crop Delivery & Gate Entry E-Pass', 105, 22, { align: 'center' });
  doc.text('Government of Uttar Pradesh & Food & Civil Supplies Dept.', 105, 28, { align: 'center' });

  // Main Card Box
  doc.setDrawColor(203, 213, 225); // Slate 300
  doc.setFillColor(248, 250, 252); // Slate 50
  doc.roundedRect(15, 40, 180, 235, 4, 4, 'FD');

  // Token Number Highlight Box
  doc.setFillColor(220, 252, 231); // Green 100
  doc.setDrawColor(34, 197, 94);
  doc.roundedRect(25, 48, 160, 26, 3, 3, 'FD');

  doc.setTextColor(21, 128, 61);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('DIGITAL TOKEN NUMBER', 105, 56, { align: 'center' });

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text(token.tokenNumber, 105, 68, { align: 'center' });

  // QR Code Box
  doc.addImage(qrDataUrl, 'PNG', 75, 78, 60, 60);

  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.setFont('helvetica', 'italic');
  doc.text('Scan at Weighbridge / Incharge Terminal for Instant Gate Check-in', 105, 142, { align: 'center' });

  // Information Table
  const startY = 152;
  const col1X = 25;
  const col2X = 110;
  const rowGap = 12;

  const infoFields = [
    { label: 'Farmer Name', value: token.farmerName, x: col1X, y: startY },
    { label: 'Mobile Number', value: `+91 ${token.phone}`, x: col2X, y: startY },

    { label: 'Procurement Centre', value: token.centreName, x: col1X, y: startY + rowGap },
    { label: 'Passbook / Reg ID', value: token.passbookNo, x: col2X, y: startY + rowGap },

    { label: 'Crop Commodity', value: token.cropName, x: col1X, y: startY + rowGap * 2 },
    { label: 'Estimated Quantity', value: `${token.quantityQuintals} Quintals`, x: col2X, y: startY + rowGap * 2 },

    { label: 'Transport Vehicle', value: `${token.vehicleType} (${token.vehicleNumber})`, x: col1X, y: startY + rowGap * 3 },
    { label: 'Allocated Date & Slot', value: `${token.slotDate} | ${token.slotTime}`, x: col2X, y: startY + rowGap * 3 },

    { label: 'Pass Issued On', value: new Date(token.issuedAt).toLocaleString(), x: col1X, y: startY + rowGap * 4 },
    { label: 'Current Status', value: token.status, x: col2X, y: startY + rowGap * 4 },
  ];

  infoFields.forEach(item => {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text(item.label.toUpperCase(), item.x, item.y);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(30, 41, 59);
    // Wrap long strings
    const splitVal = doc.splitTextToSize(String(item.value), 75);
    doc.text(splitVal, item.x, item.y + 5);
  });

  // Security Note & Instructions
  doc.setFillColor(254, 243, 199); // Amber 100
  doc.setDrawColor(245, 158, 11);
  doc.roundedRect(25, 225, 160, 24, 2, 2, 'FD');

  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(146, 64, 14);
  doc.text('IMPORTANT INSTRUCTIONS FOR FARMERS:', 28, 231);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.text('1. Bring clean, dried grain (Moisture must be below specified limit).', 28, 236);
  doc.text('2. Keep your original Aadhaar and Bank Passbook ready for direct DBT payment.', 28, 241);
  doc.text('3. Reach the centre 15 minutes before your scheduled slot time.', 28, 246);

  // Footer watermark
  doc.setFontSize(7);
  doc.setTextColor(148, 163, 184);
  doc.text(`Generated by Kisan H System | Token Hash: ${Math.random().toString(36).substring(2, 12).toUpperCase()} | Page 1 of 1`, 105, 285, { align: 'center' });

  // Save the PDF
  doc.save(`KisanH_Pass_${token.tokenNumber}.pdf`);
}
