// @ts-ignore
import { MSP_CATALOG, INITIAL_CENTRES, INITIAL_TOKENS, INITIAL_ANNOUNCEMENTS } from '../server/seedData.js';

export { MSP_CATALOG, INITIAL_CENTRES, INITIAL_TOKENS, INITIAL_ANNOUNCEMENTS };
